### PR TITLE
Activate automatic PyPI publication

### PR DESCRIPTION
**Pull request by tapastro**
Enable github action to activate PyPI publication.

### CODE REVIEW

**Comment by tapastro** [comment]
Context: https://github.com/spacetelescope/action-publish_to_pypi

**Comment by tapastro** [comment]
It looks like we can define a "secret" which will allow for publishing to PyPI Test: https://github.com/spacetelescope/action-publish_to_pypi#testing-the-workflow

I can add that here.

**Comment by jotaylor** [comment]
@tapastro Okay, I added you as a maintainer, let me know if that is high enough access. Otherwise I can make you an admin.

**Comment by tapastro** [comment]
That let me view the Settings tab, but it's missing the Secrets page within. If you'd rather not make me an admin, I can send the instructions along, but either works for me!

**Comment by jotaylor** [comment]
No problem to make you an admin! Try now.

**Comment by tapastro** [comment]
Alright, the secret is set such that our releases will initially go to https://test.pypi.org rather than the real index. We'll just have to remove that PYPI_TEST secret once we're confident in our build-ability.

**Review by jotaylor — APPROVED** [review]

**Pull request merged**
