### PR TITLE
Massive star alias updates

### PR DESCRIPTION
**Pull request by Rplesha**
Updates from Alex's latest email for the extra massive star names. This will be consistent with his version of the metadata file now.

Additionally went through the latest commits (since the creation of the single alias file) to ensure there were no mistakes. One mistake was found that a "5" appears to have been accidentally deleted, so that was added back into the alias. (GAIA DR3 4657277616048732544)

I also went through and tried to clean up some of the repeats in the aliases, but there are still a lot more. It isn't essential that each row only has unique values, so I stopped this effort to move to other tasks that still need to be done. This can be finished in the future if desired.

### CODE REVIEW

**Review by jduval82 — CHANGES_REQUESTED** [review]
There are cases where an alias was removed because I am guessing you thought they were duplicates, but they were not. So an alias is now missing. This is because some aliases are in a '|' separated list. Those will need to be restored:
AV 148
AV 479
AV 261
AV 6
AV 307
AV 498
AV 296
MCPS 083... (the version without the 5 at the end of the ra number is gone)

**Comment by Rplesha** [comment]
@jduval82 I don't believe I removed any where there was a | separator. Can you point to a location that I did? 

AV 296 for example was in target_name_ullyses and alias4, as well as in alias3 as AV 296|[M2002]_52948. I removed the alias4, but left the alias 3 value.

The MCPS 083 target is the one I mention where we had accidentally stripped the 5 earlier: https://github.com/spacetelescope/ullyses-utils/commit/4a2b0a2ea12c4d10de976588223fa4897ffb80d7

**Comment by jduval82** [comment]
> @jduval82 I don't believe I removed any where there was a | separator. Can you point to a location that I did?
> 
> AV 296 for example was in target_name_ullyses and alias4, as well as in alias3 as AV 296|[M2002]_52948. I removed the alias4, but left the alias 3 value.
> 
> The MCPS 083 target is the one I mention where we had accidentally stripped the 5 earlier: [4a2b0a2](https://github.com/spacetelescope/ullyses-utils/commit/4a2b0a2ea12c4d10de976588223fa4897ffb80d7)



> @jduval82 I don't believe I removed any where there was a | separator. Can you point to a location that I did?
> 
> AV 296 for example was in target_name_ullyses and alias4, as well as in alias3 as AV 296|[M2002]_52948. I removed the alias4, but left the alias 3 value.
> 
> The MCPS 083 target is the one I mention where we had accidentally stripped the 5 earlier: [4a2b0a2](https://github.com/spacetelescope/ullyses-utils/commit/4a2b0a2ea12c4d10de976588223fa4897ffb80d7)

**Comment by Rplesha** [comment]
AV 6 is the target_name_ullyses though (first entry), so it is in the alias file still. As a sanity check, with this version of the setup.py file on this branch:
```
In [2]: match_aliases('AV 6')
Out[2]: 'AV-6'
```

I don't feel extremely strongly about including this clean up, so if you prefer to revert back a commit, I can also do that. I was thinking that for closeout that this would be a bit cleaner to leave it, but it is a lot of work to change them and then work to review them all, too. I did not get any warnings when running the calibration database file creation code, however, and if there were any issues with aliases, I would have gotten them there for both the target databases and HLSP name assignments with match_aliases for existing data.

**Comment by jduval82** [comment]
> AV 6 is the target_name_ullyses though (first entry), so it is in the alias file still. As a sanity check, with this version of the setup.py file on this branch:
> 
> ```
> In [2]: match_aliases('AV 6')
> Out[2]: 'AV-6'
> ```
> 
> I don't feel extremely strongly about including this clean up, so if you prefer to revert back a commit, I can also do that. I was thinking that for closeout that this would be a bit cleaner to leave it, but it is a lot of work to change them and then work to review them all, too. I did not get any warnings when running the calibration database file creation code, however, and if there were any issues with aliases, I would have gotten them there for both the target databases and HLSP name assignments with match_aliases for existing data.

Oh gosh, yes of course! We are all good then (except I need to increase my contacts' correction :) ). No need to revert back. And the changes requested by Alex look good

**Review by jduval82 — APPROVED** [review]

**Pull request merged**
