### PR TITLE
This file was mistakenly deleted before, adding it back in

### PR DESCRIPTION
**Pull request by jotaylor**
My bad! 😅

### CODE REVIEW

**Comment by Rplesha** [comment]
@jotaylor what is this file used for?

**Comment by jotaylor** [comment]
> @jotaylor what is this file used for?

It contains the "official" coordinates put into the HLSP headers.

**Comment by Rplesha** [comment]
Does the script that creates it (presumably from the database files?) need to be updated with the new column names?

**Comment by jotaylor** [comment]
Great point, I just noticed this file was generated with old code, so I remade it (torturously enough, it is created in the web repo...). No code changes were necessary.

**Review by Rplesha — APPROVED** [review]
Sounds good. Merge away!

**Pull request merged**
