### PR TITLE
Massive star db updates

### PR DESCRIPTION
**Pull request by Rplesha**
Committing Alex's version of the high mass metadata file.

Tagging @jduval82 to make sure I made the alias changes correctly! 

Tagging @ariedel to let you know this change should help on your end with the ingestion as well. I think you are also good to remake the comma separated column that was created for the catalog once this is merged into main. We should not have any more alias updates unless you find any errors.

### CODE REVIEW

**Review by jduval82 — COMMENTED** [review]
It is impossible to look at the detailed changes to the massive star DB file, so I trust that the tests show it is all good to go. 

in the alias file, I noticed the VFTS 96 shows up as a red ("-") row in the files changed, but not in green. Not sure what's going on there since that row still appears to be there when looking at the file in the massive-star-db-updates branch

**Comment by Rplesha** [comment]
Thanks @jduval82! I noticed that it was a duplicate line with line 60 in the alias file, so that's why the line looks like it's deleted.

**Comment by jduval82** [comment]
> Thanks @jduval82! I noticed that it was a duplicate line with line 60 in the alias file, so that's why the line looks like it's deleted.

Ah, makes sense. All good then! Should I

**Comment by jduval82** [comment]
> Thanks @jduval82! I noticed that it was a duplicate line with line 60 in the alias file, so that's why the line looks like it's deleted.

Ah, makes sense. All good then. Should I go ahead and approve this PR, or let Jo look at it?

**Review by jotaylor — APPROVED** [review]
Looks good to me!

**Pull request merged**
