### PR TITLE
Simbad links added to CSV

### PR DESCRIPTION
**Pull request by Rplesha**
Adding in the simbad links to a new column as a temporary measure before merging the DB name file with these for the website

There also appears to be some extra floating digits that were removed on Julia's branch that I originally started working from.

This is in conjunction with the simbad_column branch on ullyses-website

### CODE REVIEW

**Comment by jotaylor** [comment]
It looks reasonable. Should it be merged after making test webpages or we can go ahead and do this PR independently?

**Comment by Rplesha** [comment]
Sorry this should be done in conjunction with https://github.com/spacetelescope/ullyses-website/pull/57, which is almost ready, but not quite

**Comment by Rplesha** [comment]
@jotaylor this is ready for review now when you have a chance

**Review by jotaylor — APPROVED** [review]
Looks good!

**Pull request merged**
