### PR TITLE
Update db tables

### PR DESCRIPTION
**Pull request by jduval82**

### CODE REVIEW

**Comment by jotaylor** [comment]
@jduval82 , this looks good to me. I undid the changes you made to the "final alias file" (pd_all_aliases.csv & pd_all_aliases.json), since this has to be made using a script. I ran that script so it should have pulled in all the changes, perhaps you want to double check it looks good though.

**Comment by jduval82** [comment]
> @jduval82 , this looks good to me. I undid the changes you made to the "final alias file" (pd_all_aliases.csv & pd_all_aliases.json), since this has to be made using a script. I ran that script so it should have pulled in all the changes, perhaps you want to double check it looks good though.



> @jduval82 , this looks good to me. I undid the changes you made to the "final alias file" (pd_all_aliases.csv & pd_all_aliases.json), since this has to be made using a script. I ran that script so it should have pulled in all the changes, perhaps you want to double check it looks good though.

@jotaylor There were still a few aliases Adric needs missing, but I think it might be because I updated the pd_all...alias file and not julia_alias_file.csv. So I just pushed a new version with those added to the julia_alias_file.csv and should be propagated by the script. Those are stars for which the ULLYSES name is e.g., N11 013 and MAST is N11-ELS-13, but Adric needed the version without the dashes, e.g., N11 ELS 13. The stars affected are NGC330 ELS 02, NGC330 ELS 04, NGC330 ROB A1, NGC330 ROB B22, N11 ELS 13, N206-FS 170 and NGC346 MPG 368

**Comment by jotaylor** [comment]
OK @jduval82, does pd_all_aliases.csv look good now? It looks like it picked up all your changes to your alias file.

**Comment by jduval82** [comment]
> OK @jduval82, does pd_all_aliases.csv look good now? It looks like it picked up all your changes to your alias file.

@jotaylor almost there! There were two more missing on my end (julia_alias), which I have added (sorry about the omission!). In addition, the N206-FS 170 is still not showing up. That one should be added by the script. This is what's in that row now:
[N206-FS]-170 | N206-FS-170 | NOT AVAILABLE IN SIMBAD | [N206-FS]-170 | N206-FS-170 | [N206-FS]-170\|[N206-FS]_170 | [N206-FS]-170 | [N206-FS]_170
There are 2 instances of [N206-FS]-170, when one should be [N206-FS] 170. Also there are 2 instances of N206-FS-170, when teh second one should be N206-FS 170

**Review by jotaylor — APPROVED** [review]
Julia and I agree things look good now.

**Pull request merged**
