### PR TITLE
New Gaia DR3

### PR DESCRIPTION
**Pull request by ariedel**
Updated file with Gaia DR3 data.

Companion database PR (because three column names change to DR3): [#15](https://grit.stsci.edu/ullyses/ullyses-database/-/merge_requests/15)

### CODE REVIEW

**Review by wfischer-stsci — APPROVED** [review]
The things changed that one would expect to change. Looks good.

**Review by jotaylor — CHANGES_REQUESTED** [review]
@wfischer-stsci do you want the DR2 columns completely removed? Or should we just add DR3 *in addition* to DR2?

**Comment by wfischer-stsci** [comment]
I think we should remove DR2. Can't imagine a case where someone would want to know what Gaia *used to* say about a target, and Gaia DR2 data will still be available elsewhere if they really do.

**Review by jotaylor — APPROVED** [review]

**Comment by ariedel** [comment]
For the most part (there are a handful of exceptions in this list) the Gaia DR3 ID is also the Gaia DR2 ID.

**Comment by ariedel** [comment]
I think Alex Fullerton's suggestion via email (change the column names to "gaia" rather than "gaia_dr3", so we never have to edit DB column names again) is sound. I'll modify the files.

**Pull request merged**
