### PR TITLE
Added Gaia Metadata to CTTS file

### PR DESCRIPTION
**Pull request by ariedel**
This PR adds Gaia metadata to the T Tauri star file for the database.
Columns filled in (for all stars from RU Lup and below):
target_name_simbad (where missing)
simbad_link (all)
targ_ra
targ_dec
coordinate_epoch
d_gaia_dr2
d_gaia_dr2_err
gaia_dr2_id
gaia_parallax
gaia_parallax_err

I also stripped a couple trailing spaces from some of the star names. Hopefully that doesn't break anything.

### CODE REVIEW

**Comment by jduval82** [comment]
Everything looks good on my end @ariedel

**Comment by jduval82** [comment]
> @jduval82 where can we find the true Simbad links for these targets? They're not on the website yet and I didn't see anything in https://github.com/spacetelescope/ullyses-utils/blob/main/utils/data/target_metadata/Taurus_sample_for_website.csv
> Or will we have to define them for the first time here?

@jotaylor I assumed @ariedel tracked them down as they were not listed anywhere. The correct links for the 4 stars are here:
UZ Tau E - http://simbad.cds.unistra.fr/simbad/sim-id?Ident=V*+UZ+TAu+E
UX Tau A - http://simbad.cds.unistra.fr/simbad/sim-id?Ident=V*+UX+TAu+a
RW Aur A - http://simbad.cds.unistra.fr/simbad/sim-id?Ident=V*+RW+Aur+A
HD104237E - http://simbad.cds.unistra.fr/simbad/sim-id?Ident=+HD+104237E

**Comment by ariedel** [comment]
Ok, links have been updated (I did pick the names SIMBAD knows them as, there, so UZ Tau E links to UZ Tau A, for instance; they're the same star). I checked against the WDS catalog to make sure I had the right star, and rechecked Gaia DR2 to make sure none of the stars were paired with the wrong Gaia DR2 entry (they weren't.)

**Comment by ariedel** [comment]
Incidentally, SIMBAD thinks UZ Tau E is HBC 53, and UZ Tau is HBC 52.

**Comment by jotaylor** [comment]
Look good now @jduval82 ?

**Comment by jduval82** [comment]
> Look good now @jduval82 ?

yes, all good @jotaylor !

**Review by jotaylor — APPROVED** [review]

**Pull request merged**
