### PR TITLE
Dr6 new ar tts

### PR DESCRIPTION
**Pull request by jduval82**

### CODE REVIEW

**Review by Rplesha — APPROVED** [review]
I'm biased, but this all looks good to me. Ready to go once we get approval on the websites and @ariedel is able to run everything on his end with this version.

**Comment by jotaylor** [comment]
This seems good (from the code perspective, which was already reviewed in Rachel's previous PR)

**Comment by jotaylor** [comment]
@jduval82 @Rplesha I suggest we merge this now so I can make HLSPs, and any further updates needed by myself or Adric can be made in subsequent PRs.

**Comment by jduval82** [comment]
> @jduval82 @Rplesha I suggest we merge this now so I can make HLSPs, and any further updates needed by myself or Adric can be made in subsequent PRs.

@jotaylor sounds good!

**Comment by Rplesha** [comment]
Seconded! Sounds good!

**Pull request merged**
